name = "clockmath"
compatibility_date = "2025-08-28"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages will look for the transformed Next.js static output here
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_GA_ID = "G-5L3QN6938D"

